language: go
sudo: false

go:
  - 1.2
  - 1.3
  - 1.4

install:
  - go get github.com/opennota/check
  - go get github.com/kisielk/gotool
  - go get golang.org/x/tools/go/types
  - go get honnef.co/go/importer
  - go build ./...

script:
  - go test -v

